include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS =  

TARGET =
TARGET_SRCS = nwk_cr_formation.c nwk_cr_join.c nwk_cr_mesh_routing.c nwk_discovery.c nwk_join.c nwk_nlme.c
USER_DEFINE = --codeseg BANK4
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk