include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 


TARGET =
TARGET_SRCS = hal_int.c hal_timer_32k.c rf_isr.c timer_isr.c uart_isr.c
#USER_DEFINE = --codeseg BANK1
SPECIFIC_COMPILE_OPTION = --int-long-rent

include $(PROJ_ROOT)/includePost.mk