include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = $(PROJ_ROOT)/rf/zb/common $(PROJ_ROOT)/rf/zb/osif 

TARGET =
TARGET_SRCS = zb_init.c
USER_DEFINE = --codeseg BANK2
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk