include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 


TARGET =
TARGET_SRCS = task_hal.c task_rf_mac.c task_rf.c
USER_DEFINE = --codeseg BANK1
#SPECIFIC_COMPILE_OPTION = --int-long-rent

include $(PROJ_ROOT)/includePost.mk