include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = $(PROJ_ROOT)/hal/int


TARGET =
TARGET_SRCS = common.c hal_clock.c hal_led.c hal_mcu.c hal_pin.c uart0.c util_buffer.c util.c
#USER_DEFINE = --codeseg BANK1

include $(PROJ_ROOT)/includePost.mk