include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = $(PROJ_ROOT)/rf/net/rime $(PROJ_ROOT)/rf/net/rpl


TARGET =
TARGET_SRCS = nbr-table.c netstack.c tcpip.c uip.c uip-debug.c uip-ds6.c uip-ds6-nbr.c uip-ds6-route.c uip-nd6.c
USER_DEFINE = --codeseg BANK1

include $(PROJ_ROOT)/includePost.mk