include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = $(PROJ_ROOT)/rf/net/mac $(PROJ_ROOT)/rf/net/rime $(PROJ_ROOT)/rf/net/rpl


TARGET =
TARGET_SRCS = nbr-table.c netstack.c packetbuf.c packetqueue.c psock.c queuebuf.c resolv.c simple-udp.c tcpip.c uip_arp.c uip.c uip-debug.c uip-ds6.c uip-ds6-nbr.c uip-ds6-route.c uip-fw.c uip-fw-drv.c uip-icmp6.c uiplib.c uip-nd6.c uip-udp-packet.c
USER_DEFINE = --codeseg BANK1

include $(PROJ_ROOT)/includePost.mk