include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 


TARGET =
TARGET_SRCS = clock.c ctimer.c etimer.c log.c rtimer.c stimer.c sys_clock.c timer.c timetable.c timetable-aggregate.c
#USER_DEFINE = --codeseg BANK1

include $(PROJ_ROOT)/includePost.mk