include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 

TARGET =
TARGET_SRCS = af_descriptor.c zdo_app.c
USER_DEFINE = --codeseg BANK2
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk