include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 

TARGET =
TARGET_SRCS = af_descriptor.c af_rx.c zdo_app.c zdo_bind_manage.c zdo_channel_manager.c zdo_common.c zdo_disc_cli.c zdo_disc_srv.c zdo_nwk_manage_srv.c
USER_DEFINE = --codeseg BANK2
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk