include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 

TARGET =
TARGET_SRCS = zb_address.c zb_bufpool_init.c zb_bufpool.c zb_ib.c zb_random.c zb_scheduler.c zb_time.c
#USER_DEFINE = --codeseg BANK2
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk