include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 

TARGET =
TARGET_SRCS = zb_bufpool_init.c zb_ib.c
USER_DEFINE = --codeseg BANK6
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk