include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 


TARGET =
TARGET_SRCS = abc.c announcement.c broadcast.c chameleon.c channel.c collect.c collect-link-estimate.c collect-neighbor.c ipolite.c mesh.c multihop.c neighbor-discovery.c netflood.c polite.c polite-announcement.c rimeaddr.c rimestats.c rmh.c route.c route-discovery.c rucb.c runicast.c stunicast.c timesynch.c trickle.c unicast.c
USER_DEFINE = --codeseg BANK2

include $(PROJ_ROOT)/includePost.mk