include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 


TARGET =
#TARGET_SRCS = list.c memb.c random.c sensors.c
TARGET_SRCS = list.c memb.c queue.c random.c
#USER_DEFINE = --codeseg BANK1

include $(PROJ_ROOT)/includePost.mk