include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = $(PROJ_ROOT)/rf/net

TARGET =
TARGET_SRCS = basic_rf_security.c basic_rf.c hal_rf_security.c hal_rf_util.c hal_rf.c
#USER_DEFINE = --codeseg BANK2
USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk