include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = $(PROJ_ROOT)/rf/zb

TARGET =
TARGET_SRCS = adc.c basic_rf.c hal_rf_security.c hal_rf_util.c hal_rf.c
USER_DEFINE = --codeseg BANK1
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk