include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = $(PROJ_ROOT)/hal $(PROJ_ROOT)/lib $(PROJ_ROOT)/os $(PROJ_ROOT)/rf $(PROJ_ROOT)/sys $(PROJ_ROOT)/task

TARGET = 
TARGET_SRCS = main.c usrmain.c

include $(PROJ_ROOT)/includePost.mk