include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS = 


TARGET =
TARGET_SRCS = rpl.c rpl-dag.c rpl-ext-header.c rpl-icmp6.c rpl-mrhof.c rpl-of0.c rpl-timers.c
USER_DEFINE = --codeseg BANK1

include $(PROJ_ROOT)/includePost.mk