include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS =  

TARGET =
TARGET_SRCS = aps_bind.c aps_commands.c aps_dups.c aps_main.c aps_nwk_confirm.c
USER_DEFINE = --codeseg BANK2
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk