include $(PROJ_ROOT)/includeEnv.mk

SUB_DIRS =  

TARGET =
TARGET_SRCS = mac_common.c mac_cr_coordinator.c mac_cr_data.c mac_data.c mac_routines.c mac.c zb_cc25xx.c
USER_DEFINE = --codeseg BANK2
#USER_DEFINE = --Werror --codeseg BANK2 

include $(PROJ_ROOT)/includePost.mk